
# Environment settings
EPISODES = 5000

# Stats settings
SHOW_PREVIEW = False
AGGREGATE_STATS_EVERY = 50

# Exploration settings
MIN_EPSILON = 0.001

# Agent settings
DISCOUNT = 0.99
REPLAY_MEMORY_SIZE = 2000
MINIBATCH_SIZE = 32
UPDATE_TARGET_EVERY = 10

# TEST

TEST_EPISODES = 100