
# Environment settings
EPISODES = 40_000
MIN_REWARD = 0

# Stats settings
SHOW_PREVIEW = False
AGGREGATE_STATS_EVERY = 50

# Exploration settings
EPSILON_DECAY = 0.99975
MIN_EPSILON = 0.001

# Agent settings
DISCOUNT = 0.99
REPLAY_MEMORY_SIZE = 50_000
MIN_REPLAY_MEMORY_SIZE = 1_000
MINIBATCH_SIZE = 64
UPDATE_TARGET_EVERY = 5
MODEL_NAME = 'dqn'